ERROR:flask_migrate:Error: Directory migrations already exists and is not empty
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:45:21] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:45:23] "GET /static/styles.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:45:24] "GET /static/script.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:45:25] "GET /static/fondo5.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:45:26] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:45:43] "GET /signin HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:45:43] "GET /static/styles2.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:45:43] "GET /static/fondo5.jpg HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:49:23] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:49:24] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:49:25] "[36mGET /static/script.js HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:49:25] "GET /static/styles.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:49:25] "GET /static/fondo5.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:49:34] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:49:34] "[36mGET /static/styles.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:49:34] "[36mGET /static/script.js HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:49:34] "[36mGET /static/fondo5.jpg HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:49:36] "GET /signin HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:49:37] "GET /static/styles2.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:49:37] "[36mGET /static/fondo5.jpg HTTP/1.1[0m" 304 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:52:11] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:52:12] "[36mGET /static/script.js HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:52:12] "[36mGET /static/styles.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:52:12] "[36mGET /static/fondo5.jpg HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:52:14] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:52:14] "[36mGET /static/styles.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:52:14] "[36mGET /static/script.js HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:52:14] "[36mGET /static/fondo5.jpg HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:52:16] "GET /signin HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:52:16] "[36mGET /static/styles2.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:52:16] "[36mGET /static/fondo5.jpg HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:52:23] "GET /signin HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:52:24] "[36mGET /static/styles2.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:52:24] "[36mGET /static/fondo5.jpg HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:52:30] "GET /signin HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:52:30] "[36mGET /static/styles2.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:52:30] "[36mGET /static/fondo5.jpg HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:53:49] "GET /signin HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:53:50] "[36mGET /static/styles2.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:53:50] "[36mGET /static/fondo5.jpg HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:54:16] "GET /signin HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:54:16] "[36mGET /static/styles2.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:54:16] "[36mGET /static/fondo5.jpg HTTP/1.1[0m" 304 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:56:19] "GET /signin HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:56:19] "[36mGET /static/styles2.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:56:19] "[36mGET /static/fondo5.jpg HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:56:22] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:56:22] "[36mGET /static/styles.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:56:22] "[36mGET /static/script.js HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:56:22] "[36mGET /static/fondo5.jpg HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:56:24] "GET /signin HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:56:24] "[36mGET /static/styles2.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:56:24] "[36mGET /static/fondo5.jpg HTTP/1.1[0m" 304 -
ERROR:app:Exception on /registro [POST]
Traceback (most recent call last):
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\routes\user\user.py", line 26, in registro
    return jsonify({"message":mensaje})
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\json\provider.py", line 215, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\json\provider.py", line 180, in dumps
    return json.dumps(obj, **kwargs)
  File "C:\Users\52867\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\52867\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\52867\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\json\provider.py", line 120, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type IntegrityError is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [29/May/2023 15:57:50] "[35m[1mPOST /registro HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [29/May/2023 16:00:16] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 16:00:16] "[36mGET /static/styles.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 16:00:16] "[36mGET /static/script.js HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 16:00:17] "[36mGET /static/fondo5.jpg HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 16:00:19] "GET /signin HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 16:00:19] "[36mGET /static/styles2.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 16:00:19] "[36mGET /static/fondo5.jpg HTTP/1.1[0m" 304 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [29/May/2023 16:06:30] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 16:06:30] "[36mGET /static/styles.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 16:06:30] "[36mGET /static/script.js HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 16:06:30] "[36mGET /static/fondo5.jpg HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 16:06:33] "GET /signin HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 16:06:33] "[36mGET /static/styles2.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 16:06:33] "[36mGET /static/fondo5.jpg HTTP/1.1[0m" 304 -
ERROR:app:Exception on /signin [POST]
Traceback (most recent call last):
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\routes\user\user.py", line 111, in registrar
    usuario = Usuario(nombre=nombre,apellido=apellido,email=email,password=password)
TypeError: __init__() got an unexpected keyword argument 'nombre'
INFO:werkzeug:127.0.0.1 - - [29/May/2023 16:06:59] "[35m[1mPOST /signin HTTP/1.1[0m" 500 -
ERROR:app:Exception on /signin [POST]
Traceback (most recent call last):
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\routes\user\user.py", line 111, in registrar
    usuario = Usuario(nombre=nombre,apellido=apellido,email=email,password=password)
TypeError: __init__() got an unexpected keyword argument 'nombre'
INFO:werkzeug:127.0.0.1 - - [29/May/2023 16:07:01] "[35m[1mPOST /signin HTTP/1.1[0m" 500 -
ERROR:app:Exception on /signin [POST]
Traceback (most recent call last):
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\routes\user\user.py", line 111, in registrar
    usuario = Usuario(nombre=nombre,apellido=apellido,email=email,password=password)
TypeError: __init__() got an unexpected keyword argument 'nombre'
INFO:werkzeug:127.0.0.1 - - [29/May/2023 16:07:03] "[35m[1mPOST /signin HTTP/1.1[0m" 500 -
ERROR:app:Exception on /signin [POST]
Traceback (most recent call last):
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\routes\user\user.py", line 111, in registrar
    usuario = Usuario(nombre=nombre,apellido=apellido,email=email,password=password)
TypeError: __init__() got an unexpected keyword argument 'nombre'
INFO:werkzeug:127.0.0.1 - - [29/May/2023 16:07:03] "[35m[1mPOST /signin HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [29/May/2023 20:49:14] "GET /signin HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 20:49:14] "[36mGET /static/styles2.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 20:49:14] "[36mGET /static/fondo5.jpg HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 20:49:24] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 20:49:24] "[36mGET /static/styles.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 20:49:24] "[36mGET /static/script.js HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 20:49:24] "[36mGET /static/fondo5.jpg HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 20:49:44] "GET /signin HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 20:49:44] "[36mGET /static/styles2.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 20:49:44] "[36mGET /static/fondo5.jpg HTTP/1.1[0m" 304 -
ERROR:app:Exception on /signin [POST]
Traceback (most recent call last):
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\routes\user\user.py", line 111, in registrar
    usuario = Usuario(nombre=nombre,apellido=apellido,email=email,password=password)
TypeError: __init__() got an unexpected keyword argument 'nombre'
INFO:werkzeug:127.0.0.1 - - [29/May/2023 20:50:06] "[35m[1mPOST /signin HTTP/1.1[0m" 500 -
ERROR:app:Exception on /signin [POST]
Traceback (most recent call last):
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\routes\user\user.py", line 111, in registrar
    usuario = Usuario(nombre=nombre,apellido=apellido,email=email,password=password)
TypeError: __init__() got an unexpected keyword argument 'nombre'
INFO:werkzeug:127.0.0.1 - - [29/May/2023 20:50:08] "[35m[1mPOST /signin HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 20:50:13] "GET /signin HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 20:50:13] "[36mGET /static/styles2.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [29/May/2023 20:50:13] "[36mGET /static/fondo5.jpg HTTP/1.1[0m" 304 -
ERROR:app:Exception on /signin [POST]
Traceback (most recent call last):
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\routes\user\user.py", line 111, in registrar
    usuario = Usuario(nombre=nombre,apellido=apellido,email=email,password=password)
TypeError: __init__() got an unexpected keyword argument 'nombre'
INFO:werkzeug:127.0.0.1 - - [29/May/2023 20:50:15] "[35m[1mPOST /signin HTTP/1.1[0m" 500 -
ERROR:app:Exception on /signin [POST]
Traceback (most recent call last):
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\routes\user\user.py", line 111, in registrar
    usuario = Usuario(nombre=nombre,apellido=apellido,email=email,password=password)
TypeError: __init__() got an unexpected keyword argument 'nombre'
INFO:werkzeug:127.0.0.1 - - [29/May/2023 20:50:15] "[35m[1mPOST /signin HTTP/1.1[0m" 500 -
ERROR:app:Exception on /signin [POST]
Traceback (most recent call last):
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\routes\user\user.py", line 111, in registrar
    usuario = Usuario(nombre=nombre,apellido=apellido,email=email,password=password)
TypeError: __init__() got an unexpected keyword argument 'nombre'
INFO:werkzeug:127.0.0.1 - - [29/May/2023 20:50:15] "[35m[1mPOST /signin HTTP/1.1[0m" 500 -
ERROR:app:Exception on /signin [POST]
Traceback (most recent call last):
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\routes\user\user.py", line 111, in registrar
    usuario = Usuario(nombre=nombre,apellido=apellido,email=email,password=password)
TypeError: __init__() got an unexpected keyword argument 'nombre'
INFO:werkzeug:127.0.0.1 - - [29/May/2023 20:50:24] "[35m[1mPOST /signin HTTP/1.1[0m" 500 -
ERROR:app:Exception on /signin [POST]
Traceback (most recent call last):
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\routes\user\user.py", line 111, in registrar
    usuario = Usuario(nombre=nombre,apellido=apellido,email=email,password=password)
TypeError: __init__() got an unexpected keyword argument 'nombre'
INFO:werkzeug:127.0.0.1 - - [29/May/2023 20:50:24] "[35m[1mPOST /signin HTTP/1.1[0m" 500 -
ERROR:app:Exception on /signin [POST]
Traceback (most recent call last):
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\routes\user\user.py", line 111, in registrar
    usuario = Usuario(nombre=nombre,apellido=apellido,email=email,password=password)
TypeError: __init__() got an unexpected keyword argument 'nombre'
INFO:werkzeug:127.0.0.1 - - [29/May/2023 20:50:25] "[35m[1mPOST /signin HTTP/1.1[0m" 500 -
ERROR:app:Exception on /signin [POST]
Traceback (most recent call last):
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\routes\user\user.py", line 111, in registrar
    usuario = Usuario(nombre=nombre,apellido=apellido,email=email,password=password)
TypeError: __init__() got an unexpected keyword argument 'nombre'
INFO:werkzeug:127.0.0.1 - - [29/May/2023 20:50:25] "[35m[1mPOST /signin HTTP/1.1[0m" 500 -
ERROR:app:Exception on /signin [POST]
Traceback (most recent call last):
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\routes\user\user.py", line 111, in registrar
    usuario = Usuario(nombre=nombre,apellido=apellido,email=email,password=password)
TypeError: __init__() got an unexpected keyword argument 'nombre'
INFO:werkzeug:127.0.0.1 - - [29/May/2023 20:50:25] "[35m[1mPOST /signin HTTP/1.1[0m" 500 -
ERROR:app:Exception on /signin [POST]
Traceback (most recent call last):
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\routes\user\user.py", line 111, in registrar
    usuario = Usuario(nombre=nombre,apellido=apellido,email=email,password=password)
TypeError: __init__() got an unexpected keyword argument 'nombre'
INFO:werkzeug:127.0.0.1 - - [29/May/2023 20:50:25] "[35m[1mPOST /signin HTTP/1.1[0m" 500 -
ERROR:app:Exception on /signin [POST]
Traceback (most recent call last):
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\routes\user\user.py", line 111, in registrar
    usuario = Usuario(nombre=nombre,apellido=apellido,email=email,password=password)
TypeError: __init__() got an unexpected keyword argument 'nombre'
INFO:werkzeug:127.0.0.1 - - [29/May/2023 20:50:26] "[35m[1mPOST /signin HTTP/1.1[0m" 500 -
ERROR:app:Exception on /signin [POST]
Traceback (most recent call last):
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\routes\user\user.py", line 111, in registrar
    usuario = Usuario(nombre=nombre,apellido=apellido,email=email,password=password)
TypeError: __init__() got an unexpected keyword argument 'nombre'
INFO:werkzeug:127.0.0.1 - - [29/May/2023 20:50:26] "[35m[1mPOST /signin HTTP/1.1[0m" 500 -
ERROR:app:Exception on /signin [POST]
Traceback (most recent call last):
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\routes\user\user.py", line 111, in registrar
    usuario = Usuario(nombre=nombre,apellido=apellido,email=email,password=password)
TypeError: __init__() got an unexpected keyword argument 'nombre'
INFO:werkzeug:127.0.0.1 - - [29/May/2023 20:50:26] "[35m[1mPOST /signin HTTP/1.1[0m" 500 -
ERROR:app:Exception on /signin [POST]
Traceback (most recent call last):
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\.venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\52867\Desktop\PROYECTO-MULTIPARA\routes\user\user.py", line 111, in registrar
    usuario = Usuario(nombre=nombre,apellido=apellido,email=email,password=password)
TypeError: __init__() got an unexpected keyword argument 'nombre'
INFO:werkzeug:127.0.0.1 - - [29/May/2023 20:50:26] "[35m[1mPOST /signin HTTP/1.1[0m" 500 -
